### ISSUE TITLE
连线异位

### ISSUE THREAD

**Issue by xuehao1997** [aliyun/data-mapping-component#19]
为什么有时打开，映射关系连线是好的。有时打开。会出现连线异位的问题。
![image](https://user-images.githubusercontent.com/36093472/117411696-71fe6100-af46-11eb-9ec2-2ee73ed1b461.png)

**Comment by noonnightstorm** [comment]
我想问问是不是还没渲染完就开始使用此组件了呢？

**Comment by xuehao1997** [comment]
> 我想问问是不是还没渲染完就开始使用此组件了呢？

好像是，加个延时就好了。有没有能判断渲染完成的标志呢？

**Comment by noonnightstorm** [comment]
这个没办法，因为我不知道你界面其他组件什么时候渲染好，例如antd的modal组件，他是有500ms的动画，是没办法判断渲染完毕的
