### ISSUE TITLE
来源表数据soureData,目标表数据targetData不支持动态传入

### ISSUE THREAD

**Issue by hanyueqiang** [aliyun/data-mapping-component#25]
场景是来源表和目标表可以切换，当切换表名后，从服务端返回该表所有字段，传入无效，页面任然是初始化传入数据

**Comment by noonnightstorm** [comment]
是不是动态传入我没做diff，是这个意思，对吧？

**Comment by hanyueqiang** [comment]
> 是不是动态传入我没做diff，是这个意思，对吧？

是的

**Comment by noonnightstorm** [comment]
好的，收到，我这两天修复一下

**Comment by noonnightstorm** [comment]
react-data-mapping@1.2.0 ， 这个版本已解决。
