### ISSUE TITLE
希望提供  @types/react-data-mapping 仓库

### ISSUE THREAD

**Issue by m1666** [aliyun/data-mapping-component#48]
TS7016: Could not find a declaration file for module 'react-data-mapping'. '/Users/maomin/Desktop/github.com/shimohq/fork/mogo/ui/node_modules/react-data-mapping/dist/index.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/react-data-mapping` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-data-mapping';`

**Comment by noonnightstorm** [comment]
ok， 收到，我们最近处理一下

**Comment by noonnightstorm** [comment]
react-data-mapping@1.3.13，你更新下即可，我会自动生成d.ts的声明文件
